config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  mount RailsAdmin::Engine => '/_system_admin_', as: 'rails_admin'
  devise_scope :user do
    root to: 'users/sessions#new'
  end

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :managers, controllers: {
    sessions:      'managers/sessions',
    passwords:     'managers/passwords',
    registrations: 'managers/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  namespace :admins do
  end

  namespace :managers do
    resources :dashboards, only: [:index]
  end

  namespace :users do
    resources :dashboards, only: [:index]
  end

  get  'inquiry/new',      to: 'inquiries#new'
  post 'inquiry',          to: 'inquiries#create'
  get  'inquiry/complete', to: 'inquiries#complete'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def new
    @form = InquiryForm.new
  end

  def create
    @form = InquiryForm.new(inquiry_params)
    if @form.save
      redirect_to inquiry_complete_path, notice: 'お問い合わせを送信いたしました'
    else
      flash['notice'] = 'お問い合わせの送信に失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  def complete; end

  private

  def inquiry_params
    params.require(:inquiry).permit(:name, :content, :type, :email)
  end
end

app/views/inquiries/complete.html.erb
<h1>Inquiries#complete</h1>
<p>Find me in app/views/inquiries/complete.html.erb</p>

app/views/inquiries/new.html.erb
<%= render "users/shared/error_messages", resource: @form %>
<div class="w-full max-w-xs">
  <%= form_with model: @form ,url: inquiry_path, scope: :inquiry, local: true, class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" do |form| %>
    <div class="mb-4">
      <%= form.label :name, 'お名前', class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.text_field :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", id: "username", type: "text", placeholder: "お名前" %>
    </div>
    <div class="mb-4">
      <%= form.label :email, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.text_field :email, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", id: "username", type: "text", placeholder: "メールアドレス" %>
    </div>
    <div class="mb-4">
      <%= form.label :type, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.select :type, options_for_select(InquiryForm::TYPE), class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", id: "username", type: "text", placeholder: "お問い合せ種別" %>
    </div>
    <div class="mb-4">
      <%= form.label :content, 'お問い合わせ内容', class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.text_area :content, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", id: "username", type: "text", placeholder: "お問合せ内容" %>
    </div>
    <%= form.submit '送信する', class:"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
  <% end %>
  <p class="text-center text-gray-500 text-xs">
    &copy;2020 Acme Corp. All rights reserved.
  </p>
</div>